let num = 1e+10;
console.log(num);
let float = 1e-5;
console.log(float);
let fromString = parseInt("20");
Math.floor(0.3);
Math.floor(0.6);
Math.ceil(0.3);
Math.ceil(0.6);
Math.round(0.3);
Math.round(0.6);
console.log(NaN === NaN);